### ISSUE TITLE
【自荐项目】Awesome-Chinese-Books

### ISSUE THREAD

**Issue by Xunzhuo** [GitHubDaily/GitHubDaily#104]
- 项目名称：

- 项目地址：https://github.com/Xunzhuo/Awesome-Chinese-Books

- 项目简介 (**100** 字以内)：一些很棒的中文技术书的PDF集合：Collections of awesome Chinese Books for Developers in PDF

- 项目截图 (**6**张以内)：
![awesome](https://user-images.githubusercontent.com/48784001/93832487-78d2af00-fca8-11ea-8a43-c260140ddf82.png)

参考 [模板](https://github.com/GitHubDaily/GitHubDaily/issues/8)

**Comment by Charmve** [comment]
贡献一个补充项目，经典必备教材和论文集

![image](https://user-images.githubusercontent.com/29084184/110734377-a9140700-8262-11eb-927f-fd5825e56e6e.png)

链接 https://github.com/Charmve/PaperWeeklyAI/tree/master/00_GuideBooksPDF(English%2BChinese)

**Comment by Xunzhuo** [comment]
Awesome！😀

Wei ZHANG <notifications@github.com> 于2021年3月11日周四 下午12:10写道：
