### ISSUE TITLE
【自荐】Algorithm-Guide：算法和数据结构系统教程（目前Stars>1000）

### ISSUE THREAD

**Issue by Xunzhuo** [GitHubDaily/GitHubDaily#111]
- 项目名称：Algorithm-Guide

- 项目地址：https://github.com/Xunzhuo/Algorithm-Guide

- 项目简介 (**100** 字以内)：【算法和数据结构教程】带你系统掌握核心知识，轻松解决面试算法难题。本仓库主要有两个分支：master分支：最近的新分支，也是以后日常维护的主分支😀，内容为算法和数据结构的教程。Collections 分支：以前的主分支，详细整理了算法和数据结构的资料，现作为辅助分支。

- 项目截图 (**6**张以内)：

![截屏2020-12-28 下午2 37 46](https://user-images.githubusercontent.com/48784001/103194359-59d46080-491a-11eb-8ed6-34fffdfb5533.png)

![截屏2020-12-28 下午2 38 48](https://user-images.githubusercontent.com/48784001/103194386-72dd1180-491a-11eb-9a69-b2a416f96334.png)

![截屏2020-12-28 下午2 38 52](https://user-images.githubusercontent.com/48784001/103194389-77092f00-491a-11eb-90b4-6a4587bbf2a6.png)

![截屏2020-12-28 下午2 38 57](https://user-images.githubusercontent.com/48784001/103194391-796b8900-491a-11eb-9787-7ed0d916520d.png)

参考 [模板](https://github.com/GitHubDaily/GitHubDaily/issues/8)

**Comment by Freelander** [comment]
感谢推荐~ 该项目已推荐过了 [地址](https://weibo.com/5722964389/J2UgHzI3S)
