### ISSUE TITLE
【自荐项目】Beerus

### ISSUE THREAD

**Issue by yuyenews** [GitHubDaily/GitHubDaily#138]
- 项目名称：Beerus

- 项目地址：[https://github.com/yuyenews](https://github.com/yuyenews)

- 项目简介 (**100** 字以内)：一个用Go开发的web解决方案，包含一个web框架，一个数据库管理框架，未来还会开发RPC以及其他的web周边组件

- 项目截图 (**6**张以内)：

![image](https://user-images.githubusercontent.com/39583360/145664396-b5ae88c1-a84f-4fad-a47a-5f535f201199.png)
![image](https://user-images.githubusercontent.com/39583360/145664401-80fb0238-cf8f-4528-a339-7da7ac32b829.png)

**Comment by BenyZheng** [comment]
这是来自QQ邮箱的自动回复邮件。您好，我已收到您的邮件，我会尽快给您回复。
