### ISSUE TITLE
机器学习原理

### ISSUE THREAD

**Issue by shunliz** [GitHubDaily/GitHubDaily#14]
- 项目名称：机器学习原理

- 项目地址：https://github.com/shunliz/Machine-Learning

- 项目简介 (**100** 字以内)：机器学习相关资料整理收集，相当全面。

- 项目截图 (**6**张以内)：

参考 [模板](https://github.com/GitHubDaily/GitHubDaily/issues/8)

**Comment by YSoer** [comment]
已推荐：https://weibo.com/5722964389/HvRMn0al7
