### ISSUE TITLE
Graphic: 可交互的 Flutter 数据可视化库

### ISSUE THREAD

**Issue by entronad** [GitHubDaily/GitHubDaily#147]
- 项目名称：Graphic

- 项目地址：https://github.com/entronad/graphic

- 项目简介：可交互的 Flutter 数据可视化库。它提供一种基于图形语法的声明式定义，可组合出多种图表类型，并提供了丰富的属性配置和交互组件。基于 Flutter 本身的图形接口实现，具有良好的性能且兼容全平台。

- 项目截图：![examples](https://github.com/entronad/graphic/raw/main/devdoc/examples.jpg)

**Comment by YSoer** [comment]
项目已收录至 [GitHubDaily 微博](https://weibo.com/5722964389/LbACshpig)
