### ISSUE TITLE
【开源自荐】 Kvrocks：基于 RocksDB 并兼容 Redis 协议的 NoSQL 数据库

### ISSUE THREAD

**Issue by git-hulk** [GitHubDaily/GitHubDaily#149]
- 项目名称：Kvrocks

- 项目地址：https://github.com/KvrocksLabs/kvrocks

- 项目简介 (**100** 字以内)：

基于 RocksDB 并兼容 Redis 协议的 NoSQL 数据库。磁盘类型的 Redis 为降低存储成本而生，存储成本可以降到 Redis 的 1/10 以上。国内使用知名公司包含百度、携程、美图、雪球等，海外如 U-Next 等等。

- 项目截图 (**6**张以内)：

![kvrocks](https://user-images.githubusercontent.com/4987594/149614389-dad02f58-3da7-424b-846b-c3cb23738a9f.jpg)

**Comment by YSoer** [comment]
项目已收录至 [GitHubDaily 微博](https://weibo.com/5722964389/LbDmVs22N)

**Comment by git-hulk** [comment]
十分感谢 @YSoer
