### ISSUE TITLE
前端技术日报，持续维护3年，希望可以推荐让更多人受益

### ISSUE THREAD

**Issue by kujian** [GitHubDaily/GitHubDaily#16]
- 项目名称：frontendDaily

- 项目地址：https://github.com/kujian/frontendDaily

- 项目简介 ：前端日报数据来自码农头条（我开发的爬虫），每日分享全网最新热门的前端开发、移动开发、设计、资源和资讯等文章，为开发者提供动力。

- 项目截图：![](https://upload-images.jianshu.io/upload_images/570843-ab41565ada6faed5.png)

参考 [模板](https://github.com/GitHubDaily/GitHubDaily/issues/8)

**Comment by Freelander** [comment]
已推荐：https://www.weibo.com/5722964389/HgTbsEnXV
