### ISSUE TITLE
豆瓣电影传送门--一款Chrome浏览器扩展

### ISSUE THREAD

**Issue by Neulana** [GitHubDaily/GitHubDaily#18]
- 项目名称：🎬豆瓣电影传送门

- 项目地址： https://github.com/Neulana/douban-movie-extension

- 项目简介：一款Chrome浏览器扩展，帮你轻松找到电影资源。

- 项目截图 (**6**张以内)：

![](https://i.loli.net/2019/02/20/5c6cdf1d02723.jpg)

**Comment by Freelander** [comment]
已推荐：https://weibo.com/5722964389/Hi60UvUqu
