### ISSUE TITLE
【开源自荐】用java开发的日志框架

### ISSUE THREAD

**Issue by jdklog** [GitHubDaily/GitHubDaily#216]
- 项目名称：jdklog

- 项目地址：https://github.com/jdkstack/jdklog

- 项目简介 (**100** 字以内)：纯java开发，无依赖，开发进行中。

- 项目截图 (**6**张以内)：

参考 [模板](https://github.com/GitHubDaily/GitHubDaily/issues/8)

**Comment by BenyZheng** [comment]
这是来自QQ邮箱的自动回复邮件。您好，我已收到您的邮件，我会尽快给您回复。
