### ISSUE TITLE
自荐 open source jobs

### ISSUE THREAD

**Issue by timqian** [GitHubDaily/GitHubDaily#25]
- 项目名称：open source jobs

- 项目地址：https://github.com/t9tio/open-source-jobs

- 项目简介 (**100** 字以内)：收集提供工作机会的开源项目

- 项目截图 (**6**张以内)：

[![]( https://raw.githubusercontent.com/timqian/images/master/Screen%20Shot%202019-03-22%20at%207.57.11%20PM.png)]( https://github.com/t9tio/open-source-jobs)

参考 [模板](https://github.com/GitHubDaily/GitHubDaily/issues/8)

**Comment by Freelander** [comment]
已推荐：https://weibo.com/5722964389/Hn1CkpzJo
