### ISSUE TITLE
自荐工大导航

### ISSUE THREAD

**Issue by brenner8023** [GitHubDaily/GitHubDaily#27]
- 项目名称：工大导航

- 项目地址：https://github.com/brenner8023/gdutnav

- 项目简介 (**100** 字以内)：工大导航的灵感来自于北邮人导航, 汕大郁金花导航等学校导航站点, 工大导航可以帮助学生快速找到需要经常访问的校内网站, 比如学校的教务系统, 学校每年的教学日历等, 工大导航同时也提供了一些非学校网站的导航, 比如腾讯动漫, 知乎等站点. 我希望工大导航能够或多或少对大家有所帮助, 更希望它可以帮助大家拓展大家的知识面.

- 项目截图 (**6**张以内)：
![Snipaste_2019-03-23_16-09-06](https://user-images.githubusercontent.com/31237954/54864273-fa820d80-4d8f-11e9-81e2-1f5b4e4db90c.png)

**Comment by mwxxhdb** [comment]
推荐 `start.me`，自定义门户导航首页
