### ISSUE TITLE
[推荐项目] OI-Wiki

### ISSUE THREAD

**Issue by ChungZH** [GitHubDaily/GitHubDaily#28]
- 项目名称：
OI-Wiki
- 项目地址：
https://github.com/24OI/OI-wiki
- 项目简介 (**100** 字以内)：
OI Wiki 致力于成为一个免费开放且持续更新的知识整合站点，大家可以在这里获取关于 编程竞赛 (competitive programming) 有趣又实用的知识，我们为大家准备了竞赛中的基础知识、常见题型、解题思路以及常用工具等内容，帮助大家更快速深入地学习编程竞赛。
- 项目截图 (**6**张以内)：
![](https://raw.githubusercontent.com/24OI/OI-wiki/master/docs/images/wordArt.png)

参考 [模板](https://github.com/GitHubDaily/GitHubDaily/issues/8)

**Comment by Freelander** [comment]
该项目已推荐过：https://weibo.com/5722964389/Ha2mA8bPA
