### ISSUE TITLE
Awesome love

### ISSUE THREAD

**Issue by glazec** [GitHubDaily/GitHubDaily#29]
- 项目名称：Awesome-love

- 项目地址：https://github.com/glazec/awesome-love

- 项目简介 (**100** 字以内)：
这是一个收录了与恋爱有关的程序，网站和故事的repo。在这程序员更加容易找到，符合他们口味的表达情感的工具。

- 项目截图 (**6**张以内)：
![image](https://user-images.githubusercontent.com/22890026/55908350-09d5c900-5b8e-11e9-805d-fb41c413d58b.png)

**Comment by YSoer** [comment]
内容太少，待更进一步完善后再做推荐。
