### ISSUE TITLE
推荐一款模块化的 Vim 配置集合 SpaceVim

### ISSUE THREAD

**Issue by wsdjeg** [GitHubDaily/GitHubDaily#31]
- 项目名称：SpaceVim

- 项目地址：https://spacevim.org  ([github](https://github.com/SpaceVim/SpaceVim), [gitee](https://gitee.com/spacevim/SpaceVim))

- 项目简介：SpaceVim 是一款模块化的 Vim 配置，使用模块的方式管理不同功能，使得这些功能的启用/禁用更加方便，对于不同编程语言的支持也是通过模块的方式来提供的。比如添加 Python 语言开发支持，只需要启用 `lang#python` 模块即可。

- 项目截图 (**6**张以内)：

**启动界面：**

![启用界面](https://user-images.githubusercontent.com/13142418/55619929-44c1b080-57cc-11e9-9c6a-8637555c2d6c.png)

**实时代码检索**

![flygrep](https://user-images.githubusercontent.com/13142418/35278709-7856ed62-0010-11e8-8b1e-e6cc6374b0dc.gif)

**快捷键导航**

![key binding guide](https://user-images.githubusercontent.com/13142418/31550099-c8173ff8-b062-11e7-967e-6378a9c3b467.gif)

**内置插件管理器**

![plugin manager](https://user-images.githubusercontent.com/13142418/34907332-903ae968-f842-11e7-8ac9-07fcc9940a53.gif)

参考 [模板](https://github.com/GitHubDaily/GitHubDaily/issues/8)

**Comment by YSoer** [comment]
已推荐：https://weibo.com/5722964389/HvO30EQXr
