### ISSUE TITLE
【开源自荐】ChatLaw：北大ChatExcel课题组开源中文法律大模型，大幅减轻幻觉问题

### ISSUE THREAD

**Issue by JessyTsu1** [GitHubDaily/GitHubDaily#315]
- 项目名称：

ChatLaw：北大ChatExcel课题组开源中文法律大模型，大幅减轻幻觉问题

- 项目地址：

https://github.com/PKU-YuanGroup/ChatLaw

- 项目简介 (**100** 字以内)：

ChatGPT浪潮下，人工智能的不断扩展和发展为LLM的扩散提供了肥沃的土壤，目前医疗、教育、金融领域已逐渐有了各自的模型，但法律领域迟迟没有明显进展。

为了促进LLM在法律甚至其他垂直应用落地的开放研究，本项目开源了中文法律大模型，并针对LLM和知识库的结合问题给出了法律场景下合理的解决方案。随后几天会有我们的产品发布

- 项目截图 (**6**张以内)：

![](https://raw.githubusercontent.com/PKU-YuanGroup/ChatLaw/main/images/webpage.png)
![](https://raw.githubusercontent.com/PKU-YuanGroup/ChatLaw/main/images/demo_3.jpg)
![](https://raw.githubusercontent.com/PKU-YuanGroup/ChatLaw/main/images/demo_1.jpg)
![](https://raw.githubusercontent.com/PKU-YuanGroup/ChatLaw/main/images/demo_2.jpg)
<div style="text-align: center;">
  <img src=https://raw.githubusercontent.com/PKU-YuanGroup/ChatLaw/main/images/elo.jpg width="200"/>
    <img src=https://raw.githubusercontent.com/PKU-YuanGroup/ChatLaw/main/images/win_rate.png width="500"/>
</div>

参考 [模板](https://github.com/GitHubDaily/GitHubDaily/issues/8)

**Comment by YSoer** [comment]
已收录至 GitHubDaily 公众号，文章链接：[ChatLaw，开源了！](https://mp.weixin.qq.com/s?__biz=MzAxOTcxNTIwNQ==&mid=2457984699&idx=1&sn=b0ac0ccf1f8733eb641fb2a9839d8218&chksm=8cb7bb51bbc03247b9aaa4a7a128eb31b16935777b5632e60109fa0ea908d70d0b31d47637c9&token=1862413643&lang=zh_CN#rd)
