### ISSUE TITLE
【开源自荐】codemap：辅助阅读源代码的工具

### ISSUE THREAD

**Issue by gpsbird** [GitHubDaily/GitHubDaily#340]
- 项目名称：codemap

- 项目地址：https://github.com/gpsbird/codemap-app

- 项目简介 (**100** 字以内)：
codemap是一款集合代码结构可视化、高亮、标注等多种辅助阅读手段，现目前已经支持javascript、typescript、c、c++、python、golang、java等多种编程语言的辅助阅读源代码工具。
通过codemap，即使是初学者也能顺利快速地阅读复杂开源项目，通过代码编辑器平铺布局、跳转结构自动连线、手动添加高亮、标注等形式，使代码结构清晰易懂，对于分析复杂项目的框架结构具有极其重大的作用，能成倍地提高用户阅读源代码的效率。

- 项目截图 (**6**张以内)：
![演示视频](https://github.com/GitHubDaily/GitHubDaily/assets/9528059/1a0483c0-aff6-444f-bd73-00cd59a60cb2)
![AnimatedDrawings-debug后_codemap](https://github.com/GitHubDaily/GitHubDaily/assets/9528059/895c4369-aac9-4eac-9129-302454ff411f)

参考 [模板](https://github.com/GitHubDaily/GitHubDaily/issues/8)

**Comment by YangFan1997** [comment]
不开源为何好意思写开源自荐？
