### ISSUE TITLE
[Flutter] Flutter GitLab Client

### ISSUE THREAD

**Issue by stefanJi** [GitHubDaily/GitHubDaily#35]
- 项目名称：F4Lab
 
- 项目地址：https://github.com/stefanJi/Flutter4GitLab

- 项目简介：
使用 Flutter 开发的 GitLab 客户端，学习 Flutter 的同时，让 GitLab 的一些操作通过 App 完成，方便程序员朋友们。

- 项目截图：

|nav|project|merge requests|
|:-:|:-:|:-:|
| ![](https://raw.githubusercontent.com/stefanJi/Flutter4GitLab/master/art/1.png) | ![](https://raw.githubusercontent.com/stefanJi/Flutter4GitLab/master/art/2.png) | ![](https://raw.githubusercontent.com/stefanJi/Flutter4GitLab/master/art/3.png) |

|merge request|commit|diff|
|:-:|:-:|:-:|
| ![](https://raw.githubusercontent.com/stefanJi/Flutter4GitLab/master/art/4.png) | ![](https://raw.githubusercontent.com/stefanJi/Flutter4GitLab/master/art/5.png) | ![](https://raw.githubusercontent.com/stefanJi/Flutter4GitLab/master/art/6.png) |

**Comment by YSoer** [comment]
已推荐：https://weibo.com/5722964389/Hv5gEuZjg
