### ISSUE TITLE
【推荐】互联网 Java 工程师进阶知识完全扫盲

### ISSUE THREAD

**Issue by acbin** [GitHubDaily/GitHubDaily#37]
- 项目名称：advanced-java

- 项目地址：https://github.com/doocs/advanced-java

- 项目简介： 互联网 Java 工程师进阶知识完全扫盲，涵盖高并发、分布式、高可用、微服务等领域知识（知识点持续更新中），GitHub star 数已突破 20k。

- 项目截图：
![图片](https://user-images.githubusercontent.com/44314231/58362763-941f8580-7ecd-11e9-9c7c-de3eb4ccb135.png)

**Comment by Freelander** [comment]
该项目已推荐过 https://weibo.com/5722964389/HbfMyC03g
