### ISSUE TITLE
[自荐] Node.js 技术栈

### ISSUE THREAD

**Issue by Q-Angelo** [GitHubDaily/GitHubDaily#47]
- 项目名称：Node.js 技术栈

- 项目地址：https://www.nodejs.red

- 项目简介：

本文档是作者从事 Node.js Developer 以来的学习历程，旨在为大家提供一个较详细的学习教程，侧重点更倾向于 Node.js 服务端所涉及的技术栈，如果本文能为您得到帮助，请给予支持！

- 项目截图 (**6**张以内)：

![image](https://user-images.githubusercontent.com/17956058/60556763-4b34d980-9d75-11e9-8e85-3c030cb53b69.png)

参考 [模板](https://github.com/GitHubDaily/GitHubDaily/issues/8)

**Comment by Freelander** [comment]
已推荐：https://weibo.com/5722964389/HBT8SfgpG
