### ISSUE TITLE
请求去掉weixin_crawler，这哥们已经闭源了

### ISSUE THREAD

**Issue by dumasss163** [GitHubDaily/GitHubDaily#51]
- 项目名称：weixin_crawler

- 项目地址：https://github.com/wonderfulsuccess/weixin_crawler

- 项目简介 (**100** 字以内)：

已经闭源，过去就是广告让加入知识星球，付费

- 项目截图 (**6**张以内)：

参考 [模板](https://github.com/GitHubDaily/GitHubDaily/issues/8)

**Comment by Freelander** [comment]
已移除
