### ISSUE TITLE
基于 Spring Boot2、Vue前后端分离的管理系统快速开发平台

### ISSUE THREAD

**Issue by Perye** [GitHubDaily/GitHubDaily#69]
- 项目名称：
dokit
- 项目地址：
https://github.com/Perye/dokit
- 项目简介 (**100** 字以内)：
基于 Spring Boot2、 Jpa、 Spring Security、JWT、redis、Vue的前后端分离的后台管理系统， 用户管理、菜单管理、角色管理、权限控制RBAC（Role-Based Access Control，基于角色的访问控制)，项目支持数据字典与数据权限管理，支持一键生成前后端代码（支持在线预览及打包下载），支持前端菜单动态路由 可一键部署服务器应用，数据库。系统中活跃用户状态监控，监视当前系统CPU、内存、磁盘、堆栈等相关信息。在线地址: http://193.112.143.187/

- 项目截图 (**6**张以内)：
![1](https://i.loli.net/2020/01/03/CplfWuMRvseBawq.png)
![1](https://i.loli.net/2020/01/03/pjOiYAzwWh1XcCd.png)
![1](https://i.loli.net/2020/01/03/3SYRoKxO7IG5BM1.png)
![1](https://i.loli.net/2020/01/03/4RjXFPCS2hizWUM.png)
![1](https://i.loli.net/2020/01/03/urnZCi7AE53pX1f.png)

参考 [模板](https://github.com/GitHubDaily/GitHubDaily/issues/8)

**Comment by zj-wukewei** [comment]
怎么看的这么熟悉？ https://github.com/elunez/eladmin？

**Comment by Freelander** [comment]
已推荐：https://weibo.com/5722964389/Iofx2eKxD
