### ISSUE TITLE
计算机基础面试问题全面总结，包含详细的follow-up question以及答案

### ISSUE THREAD

**Issue by wolverinn** [GitHubDaily/GitHubDaily#70]
- 项目名称：
计算机基础面试问题总结
- 项目地址：
https://github.com/wolverinn/Waking-Up
- 项目简介：
这份资源整理了计算机开发岗位的面试当中，涉及**计算机网络、操作系统、数据库**等计算机基础的常见面试题及答案，大部分问题都**带有更加细节的知识点追问**。可以用于模拟面试、面试前复习、快速备战面试。作者通过这个笔记，在一个月内快速准备面试中涉及到的计算机基础问题，一个月后拿到了字节跳动的后端开发offer.
- 项目截图：
![screenshot-github.com-2020.01.03-18_55_15.png](https://upload-images.jianshu.io/upload_images/10634927-0e729e2676eeac69.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

![screenshot-github.com-2020.01.03-18_55_38.png](https://upload-images.jianshu.io/upload_images/10634927-4933c942a6b2dc7c.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

**Comment by Freelander** [comment]
已推荐：https://weibo.com/5722964389/InSWFA3DA
