### ISSUE TITLE
[开源项目自荐] MQTTX 一款跨平台的 MQTT 桌面客户端

### ISSUE THREAD

**Issue by ysfscream** [GitHubDaily/GitHubDaily#76]
- 项目名称：
	MQTTX

- 项目地址：
	https://github.com/emqx/MQTTX

- 项目简介 (**100** 字以内)：
	MQTTX 是 [EMQ](https://github.com/emqx/emqx) 开源的一款跨平台 MQTT 桌面客户端。采用了聊天界面形式，简化了页面操作逻辑，方便用户快速测试 MQTT/MQTTS 连接和消息发布订阅。

- 项目截图 (**6**张以内)：

![image](https://user-images.githubusercontent.com/21299158/73834846-643fc480-4847-11ea-9154-c1e3586fe702.png)

![image](https://user-images.githubusercontent.com/21299158/73834923-85081a00-4847-11ea-90eb-fb2c6eccfbe7.png)

![image](https://user-images.githubusercontent.com/21299158/73834494-cc41db00-4846-11ea-8104-810a80f1f7b1.png)

参考 [模板](https://github.com/GitHubDaily/GitHubDaily/issues/8)

**Comment by BinZhiZhu** [comment]
是直接把dashboard搬过来是吧 :狗头

**Comment by ysfscream** [comment]
@BinZhiZhu 哈哈哈 和 dashboard 不一样呀🤨

**Comment by ysfscream** [comment]
@BinZhiZhu 哈哈哈 和 dashboard 不一样呀🤨
