### ISSUE TITLE
Deepo：一行命令搞定深度学习环境

### ISSUE THREAD

**Issue by ufoym** [GitHubDaily/GitHubDaily#80]
- 项目名称：deepo

- 项目地址：https://github.com/ufoym/deepo

- 项目简介 (**100** 字以内)：苦于安装配置各种深度学习框架？一行命令搞定！该项目包含theano / tensorflow / sonnet / pytorch / keras / lasagne / mxnet / cntk / chainer / caffe / caffe2 / torch / darknet等常用深度学习框架及其组合的镜像，以及构建这些镜像的脚本，并提供深度学习环境定制化的方案。目前docker pull已接近18万。

- 项目截图 (**6**张以内)：

![deepo](https://user-images.githubusercontent.com/2270240/32102393-aecf573c-bb4e-11e7-811c-dc673cae7b9c.png)

**Comment by YSoer** [comment]
[已推荐](https://www.weibo.com/5722964389/J2VQ7tcNp)
