### ISSUE TITLE
【自荐】一个流量转发加速工具

### ISSUE THREAD

**Issue by esrrhs** [GitHubDaily/GitHubDaily#85]
- 项目名称：
pingtunnel
- 项目地址：
https://github.com/esrrhs/pingtunnel
- 项目简介 (**100** 字以内)：
pingtunnel是把tcp/udp/sock5流量伪装成icmp流量进行转发的工具。用于突破网络封锁，或是绕过WIFI网络的登陆验证，或是在某些网络加快网络传输速度。
- 项目截图 (**6**张以内)：
![image](https://raw.githubusercontent.com/esrrhs/pingtunnel/master/network.jpg)

参考 [模板](https://github.com/GitHubDaily/GitHubDaily/issues/8)

**Comment by 88250** [comment]
和 https://github.com/GitHubDaily/GitHubDaily/issues/68 重复了吧。
