### ISSUE TITLE
【自荐】 算法竞赛资料整理汇总：算法、数据结构课件、论文集、经典书籍、OJ、面试刷题网站、习题

### ISSUE THREAD

**Issue by Xunzhuo** [GitHubDaily/GitHubDaily#86]
- 项目名称：OI_Sharing

- 项目地址：https://github.com/Xunzhuo/OI_Sharing

- 项目简介 (**100** 字以内)：全面收集、整理了算法、数据结构学习的课件、论文集、经典书籍（算法、C/C++、Python）、OnlineJudge网站、习题等

- 项目截图 (**6**张以内)：

目录梗概：
![main](https://user-images.githubusercontent.com/48784001/80869522-94c2bd80-8cd3-11ea-9220-a9e1a2b2978f.png)

Online Judge 网站汇总：
![2](https://user-images.githubusercontent.com/48784001/80867551-46a7bd00-8cc7-11ea-8730-f5a76be24b4d.png)

详细文件目录：
![1](https://user-images.githubusercontent.com/48784001/80867561-558e6f80-8cc7-11ea-8384-49da715d2630.png)

**Comment by YSoer** [comment]
[已推荐](https://www.weibo.com/5722964389/J2UgHzI3S)

**Comment by Xunzhuo** [comment]
3ks
