### ISSUE TITLE
[自荐] 《Pragmatic Programmer》中文翻译

### ISSUE THREAD

**Issue by caicaishmily** [GitHubDaily/GitHubDaily#87]
- 项目名称：
《Pragmatic Programmer》中文翻译
- 项目地址：
https://github.com/caicaishmily/pragmatic-programmer-zh
- 项目简介 (**100** 字以内)：
历时两个月将 《Pragmatic Programmer》翻译成中文 里面有一些话题我觉得对开发者蛮有启发的

**Comment by YSoer** [comment]
已推荐：

https://github.com/GitHubDaily/GitHubDaily/issues/87

**Comment by sanbeichahegongheguo** [comment]
链接失效了。
