### ISSUE TITLE
[自荐] INFO-SPIDER 集众多数据源的爬虫工具箱

### ISSUE THREAD

**Issue by kangvcar** [GitHubDaily/GitHubDaily#99]
- 项目名称： INFO-SPIDER

- 项目地址：[https://github.com/kangvcar/InfoSpider](https://github.com/kangvcar/InfoSpider)

- 使用说明文档： [https://infospider.vercel.app/](https://infospider.vercel.app/)

- 项目简介：INFO-SPIDER 是一个集众多数据源于一身的爬虫工具箱，旨在安全快捷的帮助用户拿回自己的数据，工具代码开源，流程透明。支持数据源包括GitHub、QQ邮箱、网易邮箱、阿里邮箱、新浪邮箱、Hotmail邮箱、Outlook邮箱、京东、淘宝、支付宝、中国移动、中国联通、中国电信、知乎、哔哩哔哩、网易云音乐、QQ好友、QQ群、生成朋友圈相册、浏览器浏览历史、12306、博客园、CSDN博客、开源中国博客、简书。

- 项目截图：
![](https://camo.githubusercontent.com/ae7b58d81cfa87edb29b942a7011f6243e26c441/68747470733a2f2f692e6c6f6c692e6e65742f323032302f30372f31392f4855446c6a6454617a4a51413668582e706e67)

**Comment by Freelander** [comment]
感谢自荐~ 已推荐 [地址](https://weibo.com/5722964389/JgXvVwOmN)
